# Use an official java runtime as a parent image
FROM java:8-jre-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY target /app

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV export CATALINA_HOME=/app/

# Run when the container launches
CMD ["java", "-jar", "engine-6.0.53-jar-with-dependencies.jar", "start"]